
[changelog]
# changelog header
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n"
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = "{% if version %}\n## [{{ version | trim_start_matches(pat: \"v\") }}] - {{ timestamp | date(format: \"%Y-%m-%d\") }}\n{% else %}\n## [Unreleased]\n{% endif %}\n\n{% for group, commits in commits %}\n### {{ group }}\n{% for commit in commits %}\n- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | split: \"\\n\" | first }}\n{% endfor %}\n{% endfor %}\n\n{% if previous_version %}\n[{{ version | trim_start_matches(pat: \"v\") }}]: {{ repository_url }}/compare/{{ previous_version }}...{{ version }}\n{% else %}\n[Unreleased]: {{ repository_url }}/compare/{{ version }}...HEAD\n{% endif %}"
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = "<!-- generated by git-cliff -->"

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
    #{ pattern = "^chore\\(version\\):.*", replace = "" },
]
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^refactor", group = "Refactor" },
    { message = "^perf", group = "Performance" },
    { message = "^test", group = "Testing" },
    { message = "^build", group = "Build" },
    { message = "^chore", group = "Chore" },
    { message = "^ci", group = "CI" },
    { message = "^style", group = "Style" },
    { message = "^revert", group = "Revert" },
]
# protect breaking changes from being skipped due to matching a different group
protect_breaking_commits = true
# filter out the commits that are not matched by commit_parsers
filter_commits = true
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# regex for skipping tags
skip_tags = "^"
# regex for ignoring tags
ignore_tags = "^"
# sort the tags chronologically
sort_tags = "date"
# sort the commits inside sections by oldest/newest first
sort_commits = "oldest"
